spring:
  profiles:
    active: dev
  datasource:
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.pwd}
    driver-class-name: net.sourceforge.jtds.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      validationQuery: select getdate() as date
      testOnReturn: false
      testOnBorrow: true
      maxIdle: -1
      minIdle: 10
      initialSize: 20
      maxTotal: 1000
      maxWaitMillis: 300000
      defaultAutoCommit: false
      testWhileIdle: false
      timeBetweenEvictionRunsMillis: 10000
      numTestsPerEvictionRun: 10
      minEvictableIdleTimeMillis: 30000
      defaultBatchSize: 1000
      defaultSchema: ${jdbc.defaultSchema}
      defaultRowPrefetch: 1000